Write-Host "START force_patch_bio_os_runner_module_v2"

$ErrorActionPreference = "Stop"
$RepoRoot = (Get-Location).Path
Write-Host "RepoRoot=$RepoRoot"

function SaveText($Path, $Text) {
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, ($Text -replace "`n", "`r`n"), $utf8)
    Write-Host "WROTE $Path"
}

function ReadNorm($Path) {
    return (Get-Content -Raw -Path $Path) -replace "`r`n", "`n"
}

function Backup($Path) {
    $bak = "$Path.bak_force_bio_os_runner_v2"
    if ((Test-Path $Path) -and -not (Test-Path $bak)) {
        Copy-Item $Path $bak
        Write-Host "BACKUP $bak"
    }
}

$HeaderPath = Join-Path $RepoRoot "include\zero_cpu\system\BioOSRunner.hpp"
$SourcePath = Join-Path $RepoRoot "src\system\BioOSRunner.cpp"
$DocPath = Join-Path $RepoRoot "docs\bio-os-runner.md"
$CMakePath = Join-Path $RepoRoot "CMakeLists.txt"
$CliPath = Join-Path $RepoRoot "tools\zero_cli.cpp"

if (-not (Test-Path $CMakePath)) { throw "CMakeLists.txt not found. Run from D:\Zero-CPU" }
if (-not (Test-Path $CliPath)) { throw "tools\zero_cli.cpp not found. Run from D:\Zero-CPU" }

$Header = @'
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace zero_cpu::system {

struct BioOSRunOptions {
    std::string directory = "examples\\bio_os";
    std::string combined_source_path;
    std::string combined_binary_path;
    std::size_t max_steps = 5000;
    bool write_generated_files = true;
};

struct BioOSRunResult {
    std::string directory;
    std::string combined_source_path;
    std::string combined_binary_path;
    std::string combined_source;

    std::size_t instruction_count = 0;
    std::size_t code_size = 0;
    std::size_t syscall_handler_pc = 0;
    std::size_t timer_handler_pc = 0;
    std::size_t stack_base = 0;
    std::size_t step_count = 0;

    bool halted = false;
    bool hit_step_limit = false;
    bool has_error = false;
    std::string error_message;

    std::size_t final_pc = 0;
    std::size_t final_sp = 0;
    std::int64_t exit_code = 0;

    std::vector<std::int64_t> debug_writes;
    std::string debug_ascii;

    std::int64_t timer_tick_count = 0;
    std::int64_t timer_interval = 0;
    int timer_vector = 0;
    std::int64_t timer_payload = 0;
    std::int64_t timer_interrupt_count = 0;
    bool timer_enabled = false;

    bool success() const {
        return halted && !has_error && !hit_step_limit;
    }
};

std::string bioOSDebugOutputAsAscii(
    const std::vector<std::int64_t>& writes
);

class BioOSRunner {
public:
    BioOSRunResult run(const BioOSRunOptions& options = {}) const;
};

} // namespace zero_cpu::system
'@

$Source = @'
#include "zero_cpu/system/BioOSRunner.hpp"

#include "zero_cpu/assembler/Assembler.hpp"
#include "zero_cpu/binary/BinaryFormat.hpp"
#include "zero_cpu/binary/BinaryProgram.hpp"
#include "zero_cpu/binary/BinaryWriter.hpp"
#include "zero_cpu/core/CPU.hpp"
#include "zero_cpu/core/DebugOutputDevice.hpp"
#include "zero_cpu/core/InterruptController.hpp"
#include "zero_cpu/core/MMIOBus.hpp"
#include "zero_cpu/core/MemoryMap.hpp"
#include "zero_cpu/core/TimerDevice.hpp"
#include "zero_cpu/isa/InstructionEncoder.hpp"

#include <cstdint>
#include <fstream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <utility>
#include <vector>

namespace zero_cpu::system {
namespace {

std::string joinPath(const std::string& directory, const std::string& fileName) {
    if (directory.empty()) {
        return fileName;
    }

    const char last = directory.back();
    if (last == '\\' || last == '/') {
        return directory + fileName;
    }

    return directory + "\\" + fileName;
}

std::string readTextFile(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) {
        throw std::runtime_error("Failed to open file: " + path);
    }

    std::ostringstream oss;
    oss << file.rdbuf();
    return oss.str();
}

void writeTextFile(const std::string& path, const std::string& text) {
    std::ofstream file(path, std::ios::binary);
    if (!file) {
        throw std::runtime_error("Failed to write file: " + path);
    }

    file << text;
}

std::string makeCombinedSource(const std::string& directory) {
    std::ostringstream source;

    source << "; Generated by Zero-CPU BioOSRunner\n";
    source << "; Source directory: " << directory << "\n\n";

    source << "; --- boot.zasm ---\n";
    source << readTextFile(joinPath(directory, "boot.zasm"));
    source << "\n\n";

    source << "; --- kernel.zasm ---\n";
    source << readTextFile(joinPath(directory, "kernel.zasm"));
    source << "\n\n";

    source << "; --- user_program.zasm ---\n";
    source << readTextFile(joinPath(directory, "user_program.zasm"));
    source << "\n";

    return source.str();
}

std::string combinedSourcePath(const BioOSRunOptions& options) {
    if (!options.combined_source_path.empty()) {
        return options.combined_source_path;
    }
    return joinPath(options.directory, "combined_boot.zasm");
}

std::string combinedBinaryPath(const BioOSRunOptions& options) {
    if (!options.combined_binary_path.empty()) {
        return options.combined_binary_path;
    }
    return joinPath(options.directory, "combined_boot.zbin");
}

std::size_t labelAddress(
    const AssembledProgram& assembled,
    const std::string& labelName,
    std::size_t codeBase
) {
    const auto it = assembled.labels.find(labelName);
    if (it == assembled.labels.end()) {
        throw std::runtime_error("BIO-OS label not found: " + labelName);
    }

    return codeBase + it->second * binary::kInstructionSize;
}

} // namespace

std::string bioOSDebugOutputAsAscii(const std::vector<std::int64_t>& writes) {
    std::string text;

    for (const std::int64_t value : writes) {
        if (value >= 32 && value <= 126) {
            text.push_back(static_cast<char>(value));
        } else if (value == 10) {
            text.push_back('\n');
        } else {
            text.push_back('.');
        }
    }

    return text;
}

BioOSRunResult BioOSRunner::run(const BioOSRunOptions& options) const {
    using namespace zero_cpu::binary;

    BioOSRunResult result;
    result.directory = options.directory;
    result.combined_source_path = combinedSourcePath(options);
    result.combined_binary_path = combinedBinaryPath(options);
    result.stack_base = memory_map::kBioOSStackBase;

    try {
        result.combined_source = makeCombinedSource(options.directory);

        if (options.write_generated_files) {
            writeTextFile(result.combined_source_path, result.combined_source);
        }

        Assembler assembler;
        AssembledProgram assembled = assembler.assembleString(result.combined_source);

        InstructionEncoder encoder;
        std::vector<std::uint8_t> code = encoder.encodeProgram(
            assembled.instructions,
            assembled.labels
        );

        result.instruction_count = assembled.instructions.size();
        result.code_size = code.size();

        BinaryProgram program;
        program.header.major_version = kMajorVersion;
        program.header.minor_version = kMinorVersion;
        program.header.endianness = BinaryEndianness::Little;
        program.header.entry_point = 0;
        program.header.code_size = static_cast<std::uint32_t>(code.size());
        program.code = std::move(code);

        if (options.write_generated_files) {
            BinaryWriter writer;
            writer.writeFile(result.combined_binary_path, program);
        }

        CPU cpu;
        auto interruptController = std::make_shared<InterruptController>();
        auto mmioBus = std::make_shared<MMIOBus>();
        auto debugOutputDevice = std::make_shared<DebugOutputDevice>();
        auto timerDevice = std::make_shared<TimerDevice>(interruptController, 44, 1000, 0);

        timerDevice->setEnabled(false);

        mmioBus->mapDevice(memory_map::kDebugOutputBase, memory_map::kDebugOutputSize, debugOutputDevice);
        mmioBus->mapDevice(memory_map::kTimerBase, memory_map::kTimerSize, timerDevice);

        cpu.loadBinaryProgram(program);
        cpu.setInterruptController(interruptController);
        cpu.setMMIOBus(mmioBus);
        cpu.clearClockedDevices();
        cpu.addClockedDevice(timerDevice);
        cpu.state().setSp(memory_map::kBioOSStackBase);

        result.syscall_handler_pc = labelAddress(assembled, "syscall_handler", cpu.binaryCodeBase());
        result.timer_handler_pc = labelAddress(assembled, "timer_handler", cpu.binaryCodeBase());

        interruptController->setVectorHandler(80, result.syscall_handler_pc);
        interruptController->setVectorHandler(44, result.timer_handler_pc);

        while (!cpu.state().halted() && result.step_count < options.max_steps) {
            cpu.step();

            if (cpu.state().hasError()) {
                result.has_error = true;
                result.error_message = cpu.state().errorMessage();
                break;
            }

            ++result.step_count;
        }

        if (!cpu.state().halted() && !result.has_error) {
            result.hit_step_limit = true;
            result.error_message = "BIO-OS step limit reached";
        }

        result.halted = cpu.state().halted();
        result.final_pc = cpu.state().pc();
        result.final_sp = cpu.state().sp();
        result.exit_code = cpu.state().registers().get(RegisterName::R7);

        result.debug_writes = debugOutputDevice->writes();
        result.debug_ascii = bioOSDebugOutputAsAscii(result.debug_writes);

        result.timer_tick_count = timerDevice->tickCount();
        result.timer_interval = timerDevice->interval();
        result.timer_vector = static_cast<int>(timerDevice->vector());
        result.timer_payload = timerDevice->payload();
        result.timer_interrupt_count = timerDevice->interruptCount();
        result.timer_enabled = timerDevice->enabled();

        return result;
    } catch (const std::exception& ex) {
        result.has_error = true;
        result.error_message = ex.what();
        return result;
    }
}

} // namespace zero_cpu::system
'@

$Doc = @'
# BioOSRunner

Shared BIO-OS execution module.

```bat
.\build\Debug\zero_cli.exe bio-os-runner-test examples\bio_os
```

Expected:

```text
BIO-OS runner module finished successfully.
Debug ASCII: BU
Timer Interrupt Count: 1
Timer Enabled: false
```
'@

SaveText $HeaderPath $Header
SaveText $SourcePath $Source
SaveText $DocPath $Doc

Backup $CMakePath
$CMake = ReadNorm $CMakePath
if (-not $CMake.Contains("src/system/BioOSRunner.cpp")) {
    if (-not $CMake.Contains("    src/binary/BinaryLoader.cpp")) {
        throw "CMake anchor not found: src/binary/BinaryLoader.cpp"
    }
    $CMake = $CMake.Replace("    src/binary/BinaryLoader.cpp", "    src/binary/BinaryLoader.cpp`n`n    src/system/BioOSRunner.cpp")
    SaveText $CMakePath $CMake
} else {
    Write-Host "SKIP CMake already patched"
}

Backup $CliPath
$Cli = ReadNorm $CliPath

if (-not $Cli.Contains('zero_cpu/system/BioOSRunner.hpp')) {
    $Cli = $Cli.Replace('#include "zero_cpu/isa/InstructionEncoder.hpp"', '#include "zero_cpu/isa/InstructionEncoder.hpp"' + "`n" + '#include "zero_cpu/system/BioOSRunner.hpp"')
}

$Func = @'
int runBioOSRunnerModuleTest(const std::string& bioOSDirectory) {
    using namespace zero_cpu::system;

    std::cout << "=== Zero-CPU BioOSRunner Module Test ===\n\n";

    BioOSRunOptions options;
    options.directory = bioOSDirectory;

    BioOSRunner runner;
    const BioOSRunResult result = runner.run(options);

    std::cout << "Directory: " << result.directory << "\n";
    std::cout << "Generated Source: " << result.combined_source_path << "\n";
    std::cout << "Generated Binary: " << result.combined_binary_path << "\n";
    std::cout << "Instruction Count: " << result.instruction_count << "\n";
    std::cout << "Code Size: " << result.code_size << " bytes\n";
    std::cout << "Syscall Handler PC: " << result.syscall_handler_pc << "\n";
    std::cout << "Timer Handler PC: " << result.timer_handler_pc << "\n";
    std::cout << "BIO-OS Stack Base: " << result.stack_base << "\n";
    std::cout << "Step Count: " << result.step_count << "\n";
    std::cout << "Final PC: " << result.final_pc << "\n";
    std::cout << "Final SP: " << result.final_sp << "\n";
    std::cout << "Exit Code: " << result.exit_code << "\n\n";

    std::cout << "Debug Writes: " << result.debug_writes.size() << "\n";
    std::cout << "Debug ASCII: " << result.debug_ascii << "\n";
    std::cout << "Timer Tick Count: " << result.timer_tick_count << "\n";
    std::cout << "Timer Interval: " << result.timer_interval << "\n";
    std::cout << "Timer Vector: " << result.timer_vector << "\n";
    std::cout << "Timer Payload: " << result.timer_payload << "\n";
    std::cout << "Timer Interrupt Count: " << result.timer_interrupt_count << "\n";
    std::cout << "Timer Enabled: " << (result.timer_enabled ? "true" : "false") << "\n\n";

    if (!result.success()) {
        std::cout << "BIO-OS runner module failed: " << result.error_message << "\n";
        return 1;
    }

    bool passed = true;

    auto expect = [&passed](const std::string& name, bool condition) {
        std::cout << (condition ? "[PASS] " : "[FAIL] ") << name << "\n";
        if (!condition) {
            passed = false;
        }
    };

    expect("BIO-OS runner halted CPU", result.halted);
    expect("BIO-OS runner debug ASCII is BU", result.debug_ascii == "BU");
    expect("BIO-OS runner captured two debug writes", result.debug_writes.size() == 2);
    expect("BIO-OS runner timer interrupt count is at least one", result.timer_interrupt_count >= 1);
    expect("BIO-OS runner timer disabled itself", !result.timer_enabled);
    expect("BIO-OS runner exit code is zero", result.exit_code == 0);

    if (!passed) {
        std::cout << "\nBIO-OS runner module test failed.\n";
        return 1;
    }

    std::cout << "\nBIO-OS runner module finished successfully.\n";
    return 0;
}

'@

if (-not $Cli.Contains("int runBioOSRunnerModuleTest(")) {
    $Cli = $Cli.Replace("void printUsage() {", $Func + "void printUsage() {")
}

if (-not $Cli.Contains('zero_cli bio-os-runner-test <bio_os_directory>')) {
    $Cli = $Cli.Replace('    std::cout << "  zero_cli run-os <bio_os_directory>\n";', '    std::cout << "  zero_cli run-os <bio_os_directory>\n";' + "`n" + '    std::cout << "  zero_cli bio-os-runner-test <bio_os_directory>\n";')
}

$Cmd = @'
            if (command == "bio-os-runner-test") {
                if (argc != 3) {
                    std::cerr << "Invalid bio-os-runner-test command.\n\n";
                    printUsage();
                    return 1;
                }

                return runBioOSRunnerModuleTest(argv[2]);
            }

'@

if (-not $Cli.Contains('command == "bio-os-runner-test"')) {
    $Cli = $Cli.Replace('            if (command == "run-os") {', $Cmd + '            if (command == "run-os") {')
}

SaveText $CliPath $Cli

$Cli2 = ReadNorm $CliPath
$CMake2 = ReadNorm $CMakePath
if (-not $Cli2.Contains('zero_cpu/system/BioOSRunner.hpp')) { throw "VERIFY FAIL include" }
if (-not $Cli2.Contains('command == "bio-os-runner-test"')) { throw "VERIFY FAIL command" }
if (-not $Cli2.Contains('runBioOSRunnerModuleTest')) { throw "VERIFY FAIL function" }
if (-not $CMake2.Contains('src/system/BioOSRunner.cpp')) { throw "VERIFY FAIL CMake" }
if (-not (Test-Path $HeaderPath)) { throw "VERIFY FAIL header file" }
if (-not (Test-Path $SourcePath)) { throw "VERIFY FAIL source file" }

Write-Host ""
Write-Host "FORCE PATCH V2 OK"
Write-Host "Run now:"
Write-Host "  cmake --build build --target zero_cli"
Write-Host "  .\build\Debug\zero_cli.exe bio-os-runner-test examples\bio_os"
