param(
    [string]$RepoRoot = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$studioPath = Join-Path $RepoRoot "studio\zero_studio.cpp"

if (-not (Test-Path $studioPath)) {
    throw "studio\zero_studio.cpp not found. Run this script from the Zero-CPU repository root."
}

$text = Get-Content -Raw -Path $studioPath
$text = $text -replace "`r`n", "`n"

$backupPath = "$studioPath.bak_studio_bio_os"

if (-not (Test-Path $backupPath)) {
    Copy-Item $studioPath $backupPath
}

if (-not $text.Contains('configureSystemDevices()')) {
    throw "Studio system panel patch is required first. Apply patch_studio_system_panel.ps1 before this patch."
}

function Replace-Once {
    param(
        [string]$Text,
        [string]$Old,
        [string]$New
    )

    if (-not $Text.Contains($Old)) {
        throw "Anchor not found: $Old"
    }

    return $Text.Replace($Old, $New)
}

if (-not $text.Contains('kIdRunBioOSButton')) {
    $text = Replace-Once `
        -Text $text `
        -Old 'constexpr int kIdClearBreakpointsButton = 1016;
' `
        -New 'constexpr int kIdClearBreakpointsButton = 1016;
constexpr int kIdRunBioOSButton = 1017;
'
}

if (-not $text.Contains('g_runBioOSButton')) {
    $text = Replace-Once `
        -Text $text `
        -Old 'HWND g_clearBreakpointsButton = nullptr;
' `
        -New 'HWND g_clearBreakpointsButton = nullptr;
HWND g_runBioOSButton = nullptr;
'
}

$bioOSHelpers = @'
std::string studioJoinPath(const std::string& directory, const std::string& fileName) {
    if (directory.empty()) {
        return fileName;
    }

    const char last = directory.back();

    if (last == '\\' || last == '/') {
        return directory + fileName;
    }

    return directory + "\\" + fileName;
}

std::string makeBioOSCombinedSource(const std::string& bioOSDirectory) {
    std::ostringstream source;

    source << "; Generated by Zero-CPU Studio BIO-OS runner\n";
    source << "; Source directory: " << bioOSDirectory << "\n\n";

    source << "; --- boot.zasm ---\n";
    source << readTextFile(studioJoinPath(bioOSDirectory, "boot.zasm"));
    source << "\n\n";

    source << "; --- kernel.zasm ---\n";
    source << readTextFile(studioJoinPath(bioOSDirectory, "kernel.zasm"));
    source << "\n\n";

    source << "; --- user_program.zasm ---\n";
    source << readTextFile(studioJoinPath(bioOSDirectory, "user_program.zasm"));
    source << "\n";

    return source.str();
}

std::size_t bioOSHandlerAddress(
    const zero_cpu::AssembledProgram& assembled,
    const std::string& labelName
) {
    using namespace zero_cpu;

    const auto it = assembled.labels.find(labelName);

    if (it == assembled.labels.end()) {
        throw std::runtime_error("BIO-OS label not found: " + labelName);
    }

    return g_cpu.binaryCodeBase() +
        it->second * binary::kInstructionSize;
}

void runLoadedBioOSProgram(std::ostringstream& log) {
    constexpr std::size_t kMaxBioOSSteps = 5000;

    std::size_t stepCount = 0;

    while (!g_cpu.state().halted() && stepCount < kMaxBioOSSteps) {
        g_cpu.step();

        if (g_cpu.state().hasError()) {
            log << "BIO-OS execution failed: "
                << g_cpu.state().errorMessage()
                << "\n";
            return;
        }

        ++stepCount;
    }

    if (!g_cpu.state().halted()) {
        log << "BIO-OS execution stopped: step limit reached.\n";
        return;
    }

    log << "BIO-OS execution finished successfully.\n";
    log << "Step Count: " << stepCount << "\n";
}

void onRunBioOSClicked() {
    using namespace zero_cpu;
    using namespace zero_cpu::binary;

    const std::string bioOSDirectory = "examples\\bio_os";
    const std::string combinedSourcePath =
        studioJoinPath(bioOSDirectory, "combined_boot.zasm");
    const std::string combinedBinaryPath =
        studioJoinPath(bioOSDirectory, "combined_boot.zbin");

    try {
        const std::string combinedSource =
            makeBioOSCombinedSource(bioOSDirectory);

        writeTextFile(combinedSourcePath, combinedSource);

        Assembler assembler;
        AssembledProgram assembled =
            assembler.assembleFile(combinedSourcePath);

        InstructionEncoder encoder;
        std::vector<std::uint8_t> code =
            encoder.encodeProgram(
                assembled.instructions,
                assembled.labels
            );

        BinaryProgram program;
        program.header.major_version = kMajorVersion;
        program.header.minor_version = kMinorVersion;
        program.header.endianness = BinaryEndianness::Little;
        program.header.entry_point = 0;
        program.header.code_size =
            static_cast<std::uint32_t>(code.size());
        program.code = std::move(code);

        BinaryWriter writer;
        writer.writeFile(combinedBinaryPath, program);

        g_cpu.loadBinaryProgram(program);
        configureSystemDevices();
        g_cpu.state().setSp(memory_map::kBioOSStackBase);

        g_interruptController->setVectorHandler(
            80,
            bioOSHandlerAddress(assembled, "syscall_handler")
        );

        g_interruptController->setVectorHandler(
            44,
            bioOSHandlerAddress(assembled, "timer_handler")
        );

        g_mode = StudioMode::Binary;
        g_programLoaded = true;
        g_loadedPath = combinedBinaryPath;

        SetWindowTextA(g_inputEdit, combinedBinaryPath.c_str());
        SetWindowTextA(g_outputEdit, combinedBinaryPath.c_str());
        setEditText(g_sourceEdit, combinedSource);

        std::ostringstream log;
        log << "[Studio BIO-OS Run]\n";
        log << "Directory: " << bioOSDirectory << "\n";
        log << "Generated Source: " << combinedSourcePath << "\n";
        log << "Generated Binary: " << combinedBinaryPath << "\n";
        log << "Instruction Count: "
            << assembled.instructions.size()
            << "\n";
        log << "Code Size: "
            << program.header.code_size
            << " bytes\n";
        log << "Syscall Handler PC: "
            << bioOSHandlerAddress(assembled, "syscall_handler")
            << "\n";
        log << "Timer Handler PC: "
            << bioOSHandlerAddress(assembled, "timer_handler")
            << "\n";
        log << "BIO-OS Stack Base: "
            << memory_map::kBioOSStackBase
            << "\n\n";

        runLoadedBioOSProgram(log);

        log << "\n";
        log << "Debug Writes: "
            << (g_debugOutputDevice
                ? g_debugOutputDevice->writes().size()
                : 0)
            << "\n";
        log << "Debug ASCII: "
            << studioDebugOutputAsAscii()
            << "\n";

        if (g_timerDevice) {
            log << "Timer Tick Count: "
                << g_timerDevice->tickCount()
                << "\n";
            log << "Timer Interrupt Count: "
                << g_timerDevice->interruptCount()
                << "\n";
            log << "Timer Enabled: "
                << studioBoolText(g_timerDevice->enabled())
                << "\n";
        }

        setEditText(g_traceEdit, log.str());
        refreshStateView();
    } catch (const std::exception& ex) {
        std::ostringstream log;
        log << "[Studio BIO-OS Run Failed]\n";
        log << "Error: " << ex.what() << "\n";

        setEditText(g_traceEdit, log.str());
        refreshStateView();
    }
}

'@

if (-not $text.Contains('void onRunBioOSClicked()')) {
    $anchor = 'void onLoadSourceClicked() {'
    if (-not $text.Contains($anchor)) {
        throw "onLoadSourceClicked anchor not found."
    }

    $text = $text.Replace($anchor, $bioOSHelpers + "`n" + $anchor)
}

if (-not $text.Contains('"Run BIO-OS"')) {
    $anchor = @'
        g_clearBreakpointsButton = CreateWindowExA(
            0,
            "BUTTON",
            "Clear BP",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            690,
            80,
            95,
            30,
            hwnd,
            controlId(kIdClearBreakpointsButton),
            nullptr,
            nullptr
        );

'@

    $insert = @'
        g_clearBreakpointsButton = CreateWindowExA(
            0,
            "BUTTON",
            "Clear BP",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            690,
            80,
            95,
            30,
            hwnd,
            controlId(kIdClearBreakpointsButton),
            nullptr,
            nullptr
        );

        g_runBioOSButton = CreateWindowExA(
            0,
            "BUTTON",
            "Run BIO-OS",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            800,
            80,
            130,
            30,
            hwnd,
            controlId(kIdRunBioOSButton),
            nullptr,
            nullptr
        );

'@

    if (-not $text.Contains($anchor)) {
        throw "Clear BP button anchor not found."
    }

    $text = $text.Replace($anchor, $insert)
}

if (-not $text.Contains('applyFont(g_runBioOSButton, font);')) {
    $text = Replace-Once `
        -Text $text `
        -Old '        applyFont(g_clearBreakpointsButton, font);
' `
        -New '        applyFont(g_clearBreakpointsButton, font);
        applyFont(g_runBioOSButton, font);
'
}

if (-not $text.Contains('controlIdValue == kIdRunBioOSButton')) {
    $anchor = @'
        if (controlIdValue == kIdClearBreakpointsButton) {
            onClearBreakpointsClicked();
            return 0;
        }

'@

    $insert = @'
        if (controlIdValue == kIdClearBreakpointsButton) {
            onClearBreakpointsClicked();
            return 0;
        }

        if (controlIdValue == kIdRunBioOSButton) {
            onRunBioOSClicked();
            return 0;
        }

'@

    if (-not $text.Contains($anchor)) {
        throw "Clear breakpoint command handler anchor not found."
    }

    $text = $text.Replace($anchor, $insert)
}

$text = $text.Replace('Zero-CPU Studio v0.7', 'Zero-CPU Studio v0.8')

if (-not $text.Contains('BIO-OS runner added.')) {
    $text = $text.Replace(
        '"System panel added.\n"',
        '"System panel added.\n"
        "BIO-OS runner added.\n"'
    )
}

if (-not $text.Contains('  6. [Run BIO-OS] runs examples\\bio_os')) {
    $text = $text.Replace(
        '"  5. [Step] or [Run]\n"',
        '"  5. [Step] or [Run]\n"
        "  6. [Run BIO-OS] runs examples\\\\bio_os\n"'
    )
}

Set-Content -Path $studioPath -Value ($text -replace "`n", "`r`n") -NoNewline

Write-Host "Patched studio\zero_studio.cpp with Studio BIO-OS runner."
Write-Host "Backup: $backupPath"
